export const INDICATOR_TEMPLATE = [
  {
    key: 'co2global',
    iconMapping: 'co2global',
    description: 'Total CO2 Emissions',
    unit: 'MtCO2',
    value: null,
  },
  {
    key: 'co2capita',
    iconMapping: 'co2capita',
    description: 'CO2 per Capita',
    unit: 'people',
    value: null,
  },
  {
    key: 'population',
    iconMapping: 'population',
    description: 'Population',
    unit: 'dân',
    value: null,
  },
    {
    key: 'gdp',
    iconMapping: 'gdp',
    description: 'GDP',
    unit: '$',
    value: null,
  },
    {
    key: 'education',
    iconMapping: 'education',
    description: 'Government Expenditure on Education',
    unit: '$',
    value: null,
  },
    {
    key: 'energy',
    iconMapping: 'energy',
    description: 'Total Energy',
    unit: 'MWh',
    value: null,
  },
    {
    key: 'cri',
    iconMapping: 'cri',
    description: 'CRI',
    unit: '',
    value: null,
  },
    {
    key: 'area',
    iconMapping: 'area',
    description: 'Area',
    unit: 'ha',
    value: null,
  },
      {
    key: 'hdi',
    iconMapping: 'hdi',
    description: 'HDI',
    unit: '',
    value: null,
  },
]
